/* src/config_cbc.h.  Generated by configure.  */
/* src/config_cbc.h.in. */

/* Version number of project */
#define CBC_VERSION "2.9.7"

/* Major Version number of project */
#define CBC_VERSION_MAJOR 2

/* Minor Version number of project */
#define CBC_VERSION_MINOR 9

/* Release Version number of project */
#define CBC_VERSION_RELEASE 7
